version: '3.8'

services:

  front_end:
    build:
      context: ./front_end
      args:
        - DOCKER_BUILDKIT=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
      - data:/app/uploads
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
      - "443:443"
      - "80:80"
      - "3000:3000"
      - "4000:4000"
    command: supervisord -c /app/supervisord.conf
    networks:
      - spaz_net
    depends_on:
      - database
      - contract_manager
      - webtorrent
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  webtorrent:
    environment:
      - PYTHONPATH=/app
    build:
      context: ./webtorrent
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "5002:5002"
    depends_on:
      - database
    volumes:
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
      - data:/app/uploads
      - hls_data:/app/static
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  database:
    build:
      context: ./database
      args:
        - DOCKER_BUILDKIT=0
    command: ["/app/entrypoint.sh"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rtmp_db
    expose:
      - "5003" 
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ssl/psychos.is:/certs:ro
      - data:/app/uploads
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  rtmp:
    build:
      context: ./rtmp
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "1935:1935"
      - "5004:5004"
      - "8080:8080"
    volumes:
      - data:/app/uploads
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
      - hls_data:/app/static
    depends_on:
      - database
      - webtorrent
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  contract_deployer:
    build: ./contract_deployer
    volumes:
      - contract_data:/contracts
      - ./blockchain/abi:/app/abi
      - ./blockchain/address:/app/address
    env_file:
      - .env
    command: ["npx", "hardhat", "run", "--network", "zksyncMainnet", "scripts/deploy.js"]
    networks:
      - spaz_net

  vpn:
    build: ./vpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "6660:6660"
    depends_on:
      - kerberos_setup
    volumes:
      - ./openvpn-data:/etc/openvpn
      - ./kerberos/output:/kerberos/output
    restart: unless-stopped
    networks:
      - spaz_net
    env_file:
      - .env

  contract_manager:
    build:
      context: ./contract_manager
    networks:
      - spaz_net
    command: python3 driver.py
    ports:
      - "5005:5005"
    depends_on:
      - vpn
      - contract_deployer
    volumes:
      - ./blockchain/abi:/app/abi
      - ./blockchain/address:/app/address
      - key_data:/app/keys
      - contract_data:/contracts
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  kerberos_setup:
    build:
      context: ./kerberos_setup
    volumes:
    - ./kerberos/output:/kerberos/output
    - ./kerberos/kdc-data:/var/lib/krb5kdc
    - ./kerberos/kdc-conf:/etc/krb5kdc
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:
    driver: local
  hls_data:
    driver: local
  contract_data:
    driver: local
  key_data:
    driver: local
    
networks:
  spaz_net:
    name: spaz_net
    driver: bridge