version: '3.8'

services:

  flask_app:
    build:
      context: ./flask_app
      args:
        - DOCKER_BUILDKIT=0
    volumes:
      - hls_data:/app/static
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
      - "443:443"
      - "80:80"
      - "3000:3000"
    command: >
      supervisord -c /app/supervisord.conf
    networks:
      - gremlin_net
    depends_on:
      - profile_db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  webtorrent_seeder:
    build:
      context: ./webtorrent
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "5002:5002"
    depends_on:
      - profile_db
    volumes:
      - hls_data:/app/static
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    networks:
      - gremlin_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  profile_db:
    build:
      context: ./profile_db
      args:
        - DOCKER_BUILDKIT=0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rtmp_db
    expose:
      - "5003"  # Internal-only access; don't use `ports` to keep it private
    volumes:
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    networks:
      - gremlin_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  rtmp:
    build:
      context: ./rtmp
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "1935:1935"
      - "5004:5004"
      - "8080:8080"
    volumes:
      - hls_data:/app/static
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    depends_on:
      - profile_db
    networks:
      - gremlin_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env
      
volumes:
  hls_data:
    driver: local

networks:
  gremlin_net:
    driver: bridge
