version: '3.8'

services:

  front_end:
    build:
      context: ./front_end
      args:
        - DOCKER_BUILDKIT=0
    volumes:
      - hls_data:/app/static
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
      - "443:443"
      - "80:80"
      - "3000:3000"
    command: >
      supervisord -c /app/supervisord.conf
    networks:
      - spaz_net
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  webtorrent:
    build:
      context: ./webtorrent
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "5002:5002"
    depends_on:
      - database
    volumes:
      - hls_data:/app/static
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  database:
    command: ["/app/entrypoint.sh"]
    build:
      context: ./database
      args:
        - DOCKER_BUILDKIT=0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rtmp_db
    expose:
      - "5003" 
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ssl/psychos.is:/certs:ro
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  rtmp:
    build:
      context: ./rtmp
      args:
        - DOCKER_BUILDKIT=0
    ports:
      - "1935:1935"
      - "5004:5004"
      - "8080:8080"
    volumes:
      - hls_data:/app/static
      - ./logs:/app/logs
      - /opt/ssl/psychos.is:/certs:ro
    depends_on:
      - database
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    env_file:
      - .env

  blockchain:
    build:
      context: ./blockchain
    command: python3 driver.py
    ports:
      - "5005:5005"
    volumes:
      - ./blockchain/abi:/app/abi
      - ./blockchain/address:/app/address
    environment:
      - SPAZ_LIVESTREAM_ABI_PATH=/app/abi/SpazLivestream.json
      - SPAZ_MODERATION_ABI_PATH=/app/abi/SpazModeration.json
      - SPAZ_LIVESTREAM_ADDRESS_FILE=/app/address/SpazLivestream.txt
      - SPAZ_MODERATION_ADDRESS_FILE=/app/address/SpazModeration.txt
    networks:
      - spaz_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"


volumes:
  hls_data:
    driver: local


networks:
  spaz_net:
    driver: bridge
